CREATE TABLE `real_estate` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `additional_sub_types` text COLLATE utf8mb4_unicode_520_ci,
  `apn_parcel_id` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `city` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `coordinates` json DEFAULT NULL,
  `country` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `highlights` text COLLATE utf8mb4_unicode_520_ci,
  `images` text COLLATE utf8mb4_unicode_520_ci,
  `land_acres` double DEFAULT NULL,
  `land_sqft` double DEFAULT NULL,
  `leased` double DEFAULT NULL,
  `overview` text COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `parking_spaces` int DEFAULT NULL,
  `price` int DEFAULT NULL,
  `price_sf` int DEFAULT NULL,
  `property_class` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `property_sub_type` text COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `property_type` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `providers` text COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `sprinklers` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `state` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `stories` int DEFAULT NULL,
  `street_address` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `tenancy` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `total_bldg_size` double DEFAULT NULL,
  `year_built` int DEFAULT NULL,
  `zipcode` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `zoning` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `street_number` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `street_name` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;